name: Update changelog 🤖📄
on:
  pull_request:
    types:
      - synchronize

jobs:
  labeler:
    name: Update changelog 🤖📄
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Bump version and push tag 🔖
        uses: moble/github-tag-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: ".*"

      - name: Create changelog text 📄
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,docs,chore,refactor,style,revert
          config_file: .github/tag-changelog-config.js

      - name: Read CHANGELOG.md 👓
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md

      - name: Write to CHANGELOG.md new info 📝
        uses: DamianReeves/write-file-action@master
        with:
          path: ./CHANGELOG.md
          contents: ${{ steps.changelog.outputs.changelog }}
          write-mode: overwrite

      - name: Write to CHANGELOG.md old info 📝
        uses: DamianReeves/write-file-action@master
        with:
          path: ./CHANGELOG.md
          contents: ${{ steps.package.outputs.content }}
          write-mode: append

      - name: Commit and push CHANGELOG.md ↗️
        uses: EndBug/add-and-commit@v9
        with:
          add: CHANGELOG.md
          message: "chore: update CHANGELOG.md [skip ci]"
          push: true
